template: true   # required for local templates    
#valuesFilePath: values.yml 

resources:
  - name: {{ Values.GitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ Values.GitRepo.gitProvider }} 
      path: {{ Values.GitRepo.path }}   
      branches:
        include: {{ Values.GitRepo.branches.include }}
  
pipelines:
  - name: {{ Values.Pipeline.name }}
    steps:
      - name: {{ Values.Step1.name }}
        type: Bash
        execution:
          onExecute:
            - echo "Executing Step ${step_name}"
            - echo "Hello world"
          onComplete:
            - echo "${step_name} Completed"
