template: true   # required for local templates    
valuesFilePath: pipelines.values.yml

pipelines:
  - name: mypipelinetemplate1
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "Executing Step ${step_name}"
            - echo "Hello world"
          onComplete:
            - echo "${step_name} Completed"
